/**
 * AI Service Interface
 *
 * Defines the contract that any AI backend must implement.
 * This decouples the rest of the codebase from the concrete model/provider.
 *
 * Planned provider: LLaMA 8B (local via llama.cpp HTTP server or Ollama,
 * or remote via a self-hosted endpoint).
 *
 * To add a provider:
 *  1. Create a class that implements IAiService (e.g. OllamaAiService)
 *  2. Register it in ai.service.ts
 *  3. No other files need to change
 */

export interface AiPromptOptions {
  /** The user/system message to send to the model */
  prompt: string;
  /** Optional system prompt / persona */
  systemPrompt?: string;
  /** Maximum number of tokens to generate (default: 512) */
  maxTokens?: number;
  /** Sampling temperature 0–1 (default: 0.7) */
  temperature?: number;
}

// ---------------------------------------------------------------------------
// Structured contract-analysis output
// ---------------------------------------------------------------------------

export interface RiscoInfo {
  nivel: 'baixo' | 'médio' | 'alto';
  score: number;
  maior_risco: string;
}

export interface Problema {
  nome: string;
  impacto: string;
  severidade: 'crítico' | 'médio' | 'baixo';
}

/**
 * Structured response returned by the AI for contract analysis.
 * Mirrors the JSON the model is instructed to produce via FILE_ANALYSIS_SYSTEM_PROMPT.
 */
export interface ContractAnalysis {
  resumo: string;
  risco: RiscoInfo;
  problemas: Problema[];
  sugestoes: string[];
  resposta_usuario: string;
}

export interface AiResponse {
  /** The raw text generated by the model */
  text: string;
  /** Parsed structured analysis (present when the system prompt requests JSON output) */
  parsed?: ContractAnalysis | null;
  /** Input tokens consumed */
  inputTokens?: number;
  /** Output tokens generated */
  outputTokens?: number;
  /** Total tokens used (input + output) */
  tokensUsed?: number;
  /** Estimated cost in USD */
  costUsd?: number;
  /** Wall-clock time spent generating (ms) */
  latencyMs?: number;
  /** The provider/model that produced the response */
  model: string;
}

export interface IAiService {
  /**
   * Send a prompt to the underlying model and return a structured response.
   * Implementations should throw descriptive errors on failure.
   */
  complete(options: AiPromptOptions): Promise<AiResponse>;

  /**
   * Returns true if the underlying model/service is reachable.
   * Used by /health or a dedicated /ai/health endpoint.
   */
  isAvailable(): Promise<boolean>;
}
